apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: django-migrate
        image: django_app:latest
        imagePullPolicy: Never
        command: ["python", "manage.py", "migrate", "--no-input"]
        envFrom:
        - secretRef:
            name: django-secrets
  backoffLimit: 4 