apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
stringData:
  SECRET_KEY: "your-super-secret-key-here"
  DATABASE_URL: "postgres://test_k8s:OwOtBep9Frut@postgres-postgresql.default.svc.cluster.local:5432/test_k8s"
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_DB: test_k8s
  POSTGRES_USER: test_k8s
  POSTGRES_PASSWORD: OwOtBep9Frut 