apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  namespace: edu-andrey-bychenkov
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: django-migrate
        image: decebell032/django-site:377ba13
        imagePullPolicy: IfNotPresent
        command: ["python", "manage.py", "migrate", "--no-input"]
        envFrom:
        - secretRef:
            name: django-secrets
  backoffLimit: 4 